### ISSUE TITLE
Permission Denial error, on Nexus 6P, Android 7.0

### ISSUE THREAD

**Issue by plastic-kai** [fishwjy/MultiType-FilePicker#1]
com.vincent.filepickersample E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
                                                                              Process: com.vincent.filepickersample, PID: 13011
                                                                              java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                  at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:153)
                                                                                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                  at java.lang.Thread.run(Thread.java:761)
                                                                               Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=13011, uid=10237 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                                  at android.os.Parcel.readException(Parcel.java:1683)
                                                                                  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                                  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                                  at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                                  at android.content.ContentResolver.query(ContentResolver.java:530)
                                                                                  at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:29)
                                                                                  at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
                                                                                  at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
                                                                                  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
                                                                                  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
                                                                                  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
                                                                                  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
                                                                                  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
                                                                                  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:133)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                  at java.lang.Thread.run(Thread.java:761)

**Comment by fishwjy** [comment]
That's true. I didn't add the Dynamic permission requirement in this library. I will add this ASAP. Thank you for your reply!

**Comment by plastic-kai** [comment]
thank you, fishwjy :) I can add it but I'm lazy... ^^

**Comment by fishwjy** [comment]
Hi, Plastic-kai, it's seems there is someone more diligent than us, and you can test this new push. Also, Thanks a lot, altaf933. :)

**Comment by fishwjy** [comment]
Hi, Plastic-kai, it's seems there is someone more diligent than us, and you can test this new push. Also, Thanks a lot, altaf933. :)
