### ISSUE TITLE
调视频选择器没有刷出数据返回崩溃

### ISSUE THREAD

**Issue by hqAnd** [fishwjy/MultiType-FilePicker#14]
android.database.StaleDataException: Attempted to access a cursor after it has been closed.
                                                                      at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:64)
                                                                      at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:70)
                                                                      at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
                                                                      at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
                                                                      at android.database.CursorWrapper.moveToNext(CursorWrapper.java:166)
                                                                      at com.vincent.filepicker.filter.callback.FileLoaderCallbacks$1.run(FileLoaderCallbacks.java:189)
                                                                      at java.lang.Thread.run(Thread.java:841)

报这种错，直接页面闪退

**Comment by hqAnd** [comment]
@fishwjy 大佬，能解决一下吗，进入视频选择器，没有数据刷新出来。返回或者确定就会出现这个问题。页面闪退。如果视频列表刷新出来了就不会出现这个问题。

**Comment by xxwn446** [comment]
解决了吗

**Comment by fishwjy** [comment]
请使用 1.0.5版本。使用之后不管还有否问题，都请在这里回复一下，我好尽快解决或者关闭此issue，谢谢

**Comment by fishwjy** [comment]
经测试，新版本在没有视频数据的情况下无崩溃现象，因此关闭此issue
