### ISSUE TITLE
RuntimeException: setDataSource failed

### ISSUE THREAD

**Issue by qinchong1988** [fishwjy/MultiType-FilePicker#15]
华为手机，android 6.0.1 选择视频模式进入后直接crash了。

调用方式
`Intent intent = new Intent(getActivity(), VideoPickActivity.class);
                        intent.putExtra(VideoPickActivity.IS_NEED_CAMERA, true);
                        intent.putExtra(Constant.MAX_NUMBER, 1);
                        startActivityForResult(intent, Constant.REQUEST_CODE_PICK_VIDEO);`

` java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
   at android.media.MediaMetadataRetriever.setDataSource(Native Method)
   at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
   at com.vincent.filepicker.filter.callback.FileLoaderCallbacks.getVideoThumb(FileLoaderCallbacks.java:371)
   at com.vincent.filepicker.filter.callback.FileLoaderCallbacks.access$200(FileLoaderCallbacks.java:57)
   at com.vincent.filepicker.filter.callback.FileLoaderCallbacks$1.run(FileLoaderCallbacks.java:237)
   at java.lang.Thread.run(Thread.java:833)`

**Comment by fishwjy** [comment]
@qinchong1988 
请使用 1.0.5版本。使用之后不管还有否问题，都请在这里回复一下，我好尽快解决或者关闭此issue，谢谢

**Comment by qinchong1988** [comment]
环境已经被我破环了，之前发生问题的时候我进入系统文件管理-视频分类里面有两个视频缩略图都没有加载出来，怀疑是视频文件受损了，所以删除了那两个文件，然后再进App，就不会crash了。已经无法再次验证了……从上面的调用log来看确实也和获取缩略图相关。如果最近有相关保护，应该问题不大。

**Comment by fishwjy** [comment]
好的，此问题我先关闭了，如再有问题，请提新的issue，谢谢！
