### ISSUE TITLE
点击录制语音按钮崩溃

### ISSUE THREAD

**Issue by keaitao0321** [fishwjy/MultiType-FilePicker#18]
`   android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.provider.MediaStore.RECORD_SOUND }
                                                                         at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1862)
                                                                         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1582)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:3830)
                                                                         at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:3787)
                                                                         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                         at com.vincent.filepicker.activity.AudioPickActivity.onOptionsItemSelected(AudioPickActivity.java:146)
                                                                         at android.app.Activity.onMenuItemSelected(Activity.java:2966)
                                                                         at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
                                                                         at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                                         at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                                         at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                                         at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
                                                                         at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
                                                                         at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
                                                                         at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                         at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                         at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                         at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                                                                         at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                                         at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                                                                         at android.view.View.performClick(View.java:4900)
                                                                         at android.view.View$PerformClick.run(View.java:20381)
                                                                         at android.os.Handler.handleCallback(Handler.java:815)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)`

**Comment by chuwe1** [comment]
同上 报错原因 No Activity found to handle Intent { act=android.provider.MediaStore.RECORD_SOUND }
这是是否要考虑加一个判断： getPackageManager()..queryIntentActivities(intent).size() > 0 才去执行？
不过这样 ==0 点击就没反应了。。。。。。。

另一个问题：选择文件ANR。

隐藏BUG：如果我手动去吧图片权限关了，再去点击拍照就会出现未授权崩溃，所以这里建议在点击拍照之前要加授权判断。。

**Comment by fishwjy** [comment]
The bug has been fixed. The modification is here:
https://github.com/fishwjy/MultiType-FilePicker/commit/c6a840878d681a05f8df87de8319fa5f77d5b0c1
