### ISSUE TITLE
Fatal Exception: android.os.FileUriExposedException: 

### ISSUE THREAD

**Issue by varunagp** [fishwjy/MultiType-FilePicker#33]
**Crashed on Android 8.0**

Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/WhatsApp/Media/WhatsApp Video/VID-20180518-WA0006.mp4 exposed beyond app through Intent.getData()
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
       at android.net.Uri.checkFileUriExposed(Uri.java:2356)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:10511)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:10465)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
       at android.app.Activity.startActivityForResult(Activity.java:4564)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
       at android.app.Activity.startActivityForResult(Activity.java:4522)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
       at android.app.Activity.startActivity(Activity.java:4883)
       at android.app.Activity.startActivity(Activity.java:4851)
       at com.vincent.filepicker.adapter.VideoPickAdapter$3.onClick(VideoPickAdapter.java:164)
       at android.view.View.performClick(View.java:6891)
       at android.view.View$PerformClick.run(View.java:26083)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Can anyone please help me to fix this ?

**Comment by fishwjy** [comment]
Thanks! Fixed.
