### ISSUE TITLE
App crash on Video play

### ISSUE THREAD

**Issue by Geet2312** [fishwjy/MultiType-FilePicker#53]
=================================================
Listed Video or Video dir is changed if I recorded video from whatsapp and save it. And again if I recorded a video from Phone camera and return back to app the Video list return to normal and  the error is gone.
====================================================

Process: com.skoolsync.app, PID: 31730
    java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/999/WhatsApp/Media/WhatsApp Video/VID-20190531-WA0002.mp4
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.vincent.filepicker.adapter.VideoPickAdapter$3.onClick(VideoPickAdapter.java:167)
        at android.view.View.performClick(View.java:6390)
        at android.view.View$PerformClick.run(View.java:25270)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by Geet2312** [comment]
Is there a way to disable the video play?

**Comment by LongLongLongLongLongLongLongLongLong** [comment]
我遇到了同样的问题。
